name: wespend
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0
  easy_localization: ^3.0.8
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  injectable: ^2.7.1+4
  get_it: ^9.2.0
  hive: ^2.2.3
  dio: ^5.9.0
  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1
  html: ^0.15.6





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  build_runner: ^2.7.1
  injectable_generator: ^2.8.1
  flutter_gen_runner: ^5.12.0
  lints: ^5.1.1

flutter_gen:
  output: lib/ui/utils/theme
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true
